### ISSUE TITLE
Tests fail in 0.8.0 and 0.8.1, but not in 0.7.7

### ISSUE THREAD

**Issue by yurivict** [rxcomm/pyaxo#25]
Running tests with ```${PYTHON_CMD} -m pytest``` on FreebSD 11.1

```
===>   py27-pyaxo-0.8.1 depends on file: /usr/local/bin/python2.7 - found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/_pytest/config.py", line 379, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/local/lib/python2.7/site-packages/py/_path/local.py", line 680, in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
ImportMismatchError: ('tests.conftest', '/home/k0rx/pyaxo/tests/conftest.py', local('/usr/ports/security/py-pyaxo/work/pyaxo-0.8.1/tests/conftest.py'))
ERROR: could not load /usr/ports/security/py-pyaxo/work/pyaxo-0.8.1/tests/conftest.py
```

**Comment by rxcomm** [comment]
Delete ```tests/__pycache__```.  I accidently left it in there in 0.8.0 and 0.8.1. New 0.8.2 doesn't have it and should run fine.
